kind: pipeline
name: build

steps:
  - name: build-and-push
    image: tttlkkkl/oss:v1.0
    pull: if-not-exists
    environment:
      accessKeyID:
        from_secret: accessKeyID
      accessKeySecret:
        from_secret: accessKeySecret
      endpoint:
        from_secret: endpoint
    commands:
      - git submodule init
      - git submodule update
      - hugo --environment=production
      - ossutil64 cp -r public oss://lihuaio/ -u