kind: pipeline
name: build

steps:
  - name: build-static
    image: gohugoio/hugo
    pull: if-not-exists
    commands:
    - hugo
  - name: build-docker-image
    image: plugins/docker
    pull: if-not-exists
    settings:
      registry: hub.docker.com
      repo: tttlkkkl/lihuaio.com
      tags: ${DRONE_TAG}
      purge: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password